### ISSUE TITLE
Unexpected exception during plugin work

### ISSUE THREAD

**Issue by terma** [jenkinsci/ec2-fleet-plugin#123]
Reported in #121

```
2019-07-15 10:08:01.206+0000 [id=55]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [docker] Fleet (docker) no longer has the instance i-0c09857bbb04db080, removing from Jenkins.
2019-07-15 10:08:01.212+0000 [id=4458832]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Unexpected removing fleet node termination but resubmit disabled, no actions, disableTaskResubmit: false, offline: true, offlineCause: class hudson.slaves.OfflineCause$SimpleOfflineCause
2019-07-15 10:08:01.213+0000 [id=55]	INFO	c.a.jenkins.ec2fleet.CloudNanny#doRun: Error during fleet FleetCloud stats update
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.updateStatus(EC2FleetCloud.java:367)
	at com.amazon.jenkins.ec2fleet.CloudNanny$1.call(CloudNanny.java:44)
	at com.amazon.jenkins.ec2fleet.CloudNanny$1.call(CloudNanny.java:41)
	at hudson.model.Queue._withLock(Queue.java:1438)
	at hudson.model.Queue.withLock(Queue.java:1299)
	at com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:41)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-15 10:08:01.214+0000 [id=4453143]	INFO	c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Unexpected removing fleet node termination but resubmit disabled, no actions, disableTaskResubmit: false, offline: true, offlineCause: class hudson.slaves.OfflineCause$SimpleOfflineCause
```

**Comment by terma** [comment]
Fixed in [1.11.2](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.11.2)
