### ISSUE TITLE
[Idea] Plugin could potentially bootup on-demand instance when spots are unavailable

### ISSUE THREAD

**Issue by Puneeth-n** [jenkinsci/ec2-fleet-plugin#130]
This is more of an Idea. [AWS announced recently](https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-ec2-fleet-modify-on-demand-target-capacity/) the ability to modify the on-demand target capacity in a spot fleet. The plugin could boot up on-demand  when spots are unavailable.

**Comment by terma** [comment]
Great idea, thx

**Comment by kandia** [comment]
Hello,

Could plugin be updated to manage both "TargetCapacity" and "OnDemandTargetCapacity". 

Current behavior manage only "TargetCapacity" and if spot-fleet have some on-demand instance running .. scale down will fail with such stacktrace :

```
com.amazonaws.services.ec2.model.AmazonEC2Exception: TargetCapacity (0) cannot be less than OnDemandTargetCapacity (1). (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameter; Request ID: XXXXXX-XXXX-XXX-XXXX-XXXXXXXXXXXXX)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1726)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1381)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:24592)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:24559)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:24548)
        at com.amazonaws.services.ec2.AmazonEC2Client.executeModifySpotFleetRequest(AmazonEC2Client.java:20158)
        at com.amazonaws.services.ec2.AmazonEC2Client.modifySpotFleetRequest(AmazonEC2Client.java:20129)
        at com.amazon.jenkins.ec2fleet.fleet.EC2SpotFleet.modify(EC2SpotFleet.java:89)
        at com.amazon.jenkins.ec2fleet.EC2FleetCloud.updateByState(EC2FleetCloud.java:463)
        at com.amazon.jenkins.ec2fleet.EC2FleetCloud.update(EC2FleetCloud.java:428)
        at com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:58)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:70)
        at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
Is it possible to add new parameter to plugin configuration:
- Miminum On-Demand Size
- Maximum On-Demand Size.
Set priority to On-Demande instance. For example when plugin should scale down, it should first terminate spot instance. When there's no more spot instance running then proceed to terminate on-demand instance 
For scale up we Should first run on-demand instance until Maximum On-Demand Size is reached, then run spot instance till Maximum Cluster Size is reached.

Thx for your help

**Comment by fluffysquirrels** [comment]
@jillmon My company has a requirement for this feature. We are looking to move to spot instances to reduce costs but if they are unavailable we would need to be able to fall back to on-demand instances to keep our builds running albeit at higher costs. It would be unacceptable to us to fail to run builds because spot instances are not available, as it would effectively stop all our engineers from working for potentially hours while we reconfigured.

Please reach out if you have further questions.
