### ISSUE TITLE
Planned capacity snapshot bug

### ISSUE THREAD

**Issue by DerkSchooltink** [jenkinsci/ec2-fleet-plugin#156]
During the setup of this plugin I ran into the following issue: no instances would be spawned because it thinks it has enough capacity in the form of so called 'planned capacity snapshots'. I'm not quite sure what this is, I can't find any clear documentation on it. The logs give me the following statement:

`currentDemand -1 availableCapacity 2 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 2 additionalPlannedCapacity 0)`

Current demand is -1, which is correct since one build is queued up and awaiting execution. But no instance will spawn so it never executes. 

Some additional information: I've had 2 on-demand instances before running alongside the spotfleet to allow for builds to not break during the installation of the spotfleet. Perhaps this is related to the planned capacity snapshot capacity? I'm quite sure if this is relevant though.

Am I missing something here? Is there documentation on the different capacity types?

**Comment by bgaillard** [comment]
Hi, we recently updated the plugin from version `1.11.1` to version `1.16.1`.

Since this update we encounter lot of problems, it works during several hours and then when no jobs are running the Fleets scale-down to 0 (all our EC2 Fleets are configure with `Min Cluster Size` equals to `0`).

A this time new jobs began to be queued and all our Fleets stays at 0 indefinitely.

Yesterday I restarted my Jenkins slave, after restart the jobs which were queued restarted correctly. This morning our job queue was clean and everything was good.

But, today at 12 am we started to see a big job queue again and all our Spot Fleets stays at 0. The Spot Fleets do not scale-up anymore.

I'm not 100% sure but it seems several persons reported similar problems : 

* In #153 the last comment indicated that a reboot was required to make it work again ; 
* In #149 a similar problem is reported, in one comment a user mentioned a restart solved the problem.

On our side we tried the following without success. 

* Changing the `No Delay Provision Strategy`, checked or unchecked the effect is the same Spot Fleet stays intact
* Changing `Minimum Cluster Size` from `0` to `1` has no effect (and nothing appears in the Spot Fleets history on AWS side)

The only thing which can make the Spot Fleet scale-up again seems to be a Jenkins restart. But after few hours the problems is their again (it seems to appear after our Spot Fleet scale down to 0).

Today I finally succeed to see strange exceptions in our logs.

```
Error during fleet micro-1.1.0 stats update
com.amazonaws.services.ec2.model.AmazonEC2Exception: targetCapacity must be an integer value greater than or equal to 0. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: d7cf11fa-63f3-4988-98d8-b0f4ddfa82dc)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:22500)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:22467)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:22456)
	at com.amazonaws.services.ec2.AmazonEC2Client.executeModifySpotFleetRequest(AmazonEC2Client.java:18360)
	at com.amazonaws.services.ec2.AmazonEC2Client.modifySpotFleetRequest(AmazonEC2Client.java:18331)
	at com.amazon.jenkins.ec2fleet.fleet.EC2SpotFleet.modify(EC2SpotFleet.java:79)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.update(EC2FleetCloud.java:409)
	at com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:62)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Here is the configuration associated to the EC2 Fleet `micro-1.1.0`. 

![image](https://user-images.githubusercontent.com/1327782/69631366-1ab84980-104e-11ea-9712-f578144aeb4d.png)

The other strange thing I see is that the EC2 Fleet Status panel cannot be opened. 

![image](https://user-images.githubusercontent.com/1327782/69632038-d8433c80-104e-11ea-955e-32bf90bc0ff5.png)

Don't know if its related but perhaps is also cause by a property which cannot be read somewhere.

Finally, just after a Jenkins restart I can also see the following exception in my logs.

```
Failed to load org.jenkinsci.plugins.github.pullrequest.extra.GitHubPRLabelUnblockQueueCondition$DescriptorImpl
java.lang.ClassNotFoundException: org.jenkinsci.plugins.blockqueuedjob.condition.BlockQueueCondition$BlockQueueConditionDescriptor
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1383)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1336)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1083)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Caused: java.lang.NoClassDefFoundError: org/jenkinsci/plugins/blockqueuedjob/condition/BlockQueueCondition$BlockQueueConditionDescriptor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1149)
	at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:712)
	at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1320)
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1373)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1336)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:81)
	at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:2041)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jvnet.hudson.annotation_indexer.Index$2$1.fetch(Index.java:99)
	at org.jvnet.hudson.annotation_indexer.Index$2$1.hasNext(Index.java:73)
	at org.jvnet.hudson.annotation_indexer.SubtypeIterator.fetch(SubtypeIterator.java:18)
	at org.jvnet.hudson.annotation_indexer.SubtypeIterator.hasNext(SubtypeIterator.java:28)
	at org.jenkinsci.plugins.structs.SymbolLookup.findDescriptor(SymbolLookup.java:140)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.DeclarativeAgentDescriptor.byName(DeclarativeAgentDescriptor.java:121)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.DeclarativeAgentDescriptor.instanceForName(DeclarativeAgentDescriptor.java:134)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.DeclarativeAgentDescriptor$instanceForName$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This exception is related to the Github plugin but I found it mentioned on the EC2 Plugin too so i'm wondering if it could be linked : https://issues.jenkins-ci.org/browse/JENKINS-54041

Hope their is enough context to track the problem, we absolutely need a fix for this because it impacts our whole team.

Thanks for your help.

**Comment by DerkSchooltink** [comment]
@bgaillard I can confirm that I have similar issues: the spot fleet panel does not work for me anymore either. It is a long shot, but do you see any logs regarding `currentDemand` in your Jenkins logs? Perhaps it is a similar issue to mine, that for some reason the plugin thinks there are instances but there are clearly not.

**Comment by bgaillard** [comment]
> do you see any logs regarding currentDemand in your Jenkins logs

Yes I see similar logs.

**Comment by DerkSchooltink** [comment]
After some further testing I think I have narrowed it down. The problem seems to occur when the spot request is being modified in rapid succession. Perhaps the spot request change request is being fired when it's already being modified or something alike.

I can see the `plannedCapacitySnapshot` being set to 3 when I queue a new build, but the EC2 management console doesn't indicate that the spot request is being updated, and it isn't. Queuing up an additional 3 builds will trigger a new instance creation, but the `plannedCapacitySnapshot` remains at 3 and is never reset to 0. Ultimately, when the builds are done the instance is removed again, but you run into the same problem when new builds queue again. 

I do have to mention though that even though this capacity bug the plugin started working all of the sudden. I did a restart of Jenkins and thought it had no effect, as it still reported the planned capacity snapshot to be at 3. The plugin did however start to launch an instance when there was a job in the queue, and it also deregistered it after the job was done. For me personally this means the issue is solved, but I can imagine @bgaillard still has troubles.

**Comment by 0xClpz** [comment]
I seem to be running into the same issues, no workers are spawned because the plugin thinks the availableCapacity is wayyy higher than what it actually is and it can only be fixed with a restart of the jenkins master

Here's a log example with around 10 jobs in the queue 

```
start
jenkins_1  | 2019-11-28 13:55:03.813+0000 [id=35]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] fleet instances [i-redacted, i-redacted]
jenkins_1  | 2019-11-28 13:55:03.873+0000 [id=35]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] described instances [i-redacted], i-redacted]]
jenkins_1  | 2019-11-28 13:55:03.873+0000 [id=35]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] jenkins nodes [i-redacted], i-redacted]]
jenkins_1  | 2019-11-28 13:55:03.873+0000 [id=35]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] jenkins nodes without instance []
jenkins_1  | 2019-11-28 13:55:03.873+0000 [id=35]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] terminated instances []
jenkins_1  | 2019-11-28 13:55:03.873+0000 [id=35]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] new instances []
jenkins_1  | 2019-11-28 13:55:04.574+0000 [id=32]	INFO	c.a.j.e.NoDelayProvisionStrategy#apply: currentDemand -17 availableCapacity 23 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 23 additionalPlannedCapacity 0)
```

The "available capacity" seems to indicate 23 are available but there's only two jenkins nodes listed by the plugin in the above logs.

**Comment by bgaillard** [comment]
Hi @DerkSchooltink @0xClpz and thanks for this additional context about this issue.

I performed a last Jenkins restart 2 / 3 days ago and since this moment we do not encounter any other scale down / up problems. Don't know why its working now, it seems restarting our Jenkins master changed a state somewhere and make it work now.

So for us the issue seems to be solved too.

**Comment by DerkSchooltink** [comment]
> Hi @DerkSchooltink @0xClpz and thanks for this additional context about this issue.
> 
> I performed a last Jenkins restart 2 / 3 days ago and since this moment we do not encounter any other scale down / up problems. Don't know why its working now, it seems restarting our Jenkins master changed a state somewhere and make it work now.
> 
> So for us the issue seems to be solved too.

Yes, a restart of Jenkins seems to be the solution. This seems to be the common denominator between all three participants' applied fixes.

**Comment by fitzy101** [comment]
I also saw this exact issue on 1.16.1, and a restart fixed it for me. Will keep an eye on it in the mean time.

**Comment by FredrikSeidl** [comment]
This is pretty much the same issue as in #149 . There is something off with the capacity calculation. Our solution for now is to add a jenkins restart every hour in crontab

**Comment by terma** [comment]
hi all, could you please check if you have ```No Delay Provision Strategy``` enabled for your fleets

**Comment by terma** [comment]
About widget info, I think we have related issue #147 based on my understanding it should happen only if you have two or more configurations (Amazon EC2 Fleet).

**Comment by fitzy101** [comment]
Hi @terma, yes  I do have that enabled.

**Comment by 0xClpz** [comment]
Same here it’s enabled, I’m restarting my Jenkins master on the daily to deal with that bug, let me know if there’s any log I can provide you with to help you fix the issue

**Comment by bgaillard** [comment]
Hi @terma.

> About widget info, I think we have related issue #147 based on my understanding it should happen only if you have two or more configurations (Amazon EC2 Fleet).

Yes, we observe the Wiget problem with 8 configurations.

> hi all, could you please check if you have No Delay Provision Strategy enabled for your fleets

I tried with and without the `No Delay Provision Strategy`. Now all our Cloud Configuration do no use the `No Delay Provision Strategy`. 

So I suppose the problem is encountered with both strategies.

**Comment by terma** [comment]
ok, I think I fixed both problems, widget and actual provision in https://github.com/jenkinsci/ec2-fleet-plugin/pull/159 will update when it will be merged

**Comment by terma** [comment]
Fixes released [1.16.2](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.16.2)
- Fix provision problems
- Avoid negative target capacity
- Correctly show fleet info widget (for multiple fleets)

**Comment by bgaillard** [comment]
> Fixes released in 1.16.2

Thanks @terma :+1: , I just installed the new version. We'll let it run during few days and come back here to let you know if the problem is fixed.

**Comment by DerkSchooltink** [comment]
I've installed it as well, the target issues seem to be resolved. The widget also displays the right information and you can actually see when the target changes and shortly after a new node is provisioned. 

Waiting for @bgaillard to confirm this before I close the issue.

**Comment by bgaillard** [comment]
> Waiting for @bgaillard to confirm this before I close the issue.

Hi, after one day it seems to work, at least the scale-up is not locked as before. The Widget bug is also solved.

But I believe their is an other bug (perhaps we should open an other issue). We have a Cloud with a `Max Cluster Size` equals to `4` but it seems to start more instances. Each day in the morning we trigger the execution of lot of jobs (~50  jobs), this is what is causing "aggressive" scale-ups. Do you observe this too ?

**Comment by DerkSchooltink** [comment]
@terma I'm closing the issue then. It seems to be resolved for the people involved in this issue! Thanks again for the quick response and fix.

**Comment by terma** [comment]
Nice, thx all for detailed information

**Comment by 0xClpz** [comment]
So far so good on our side, no issues with scaling anymore, thank you very much!! 🙌🎉

**Comment by almiroshnich** [comment]
Wanted to say thanks for fixing the bug, nice job!

Also, I'm wondering if anybody noticed significantly increased number of blocked threads at jenkins-master while scaling happens? I'm clearly seeing a correlation with rolling out plugin upgrade yesterday...

**Comment by terma** [comment]
@almiroshnich interesting up or down? Plugin doesn't create new threads, however during scale up plugins (as any other cloud plugins) creates ```PlannedNode``` which effectively is ```Future``` probably Jenkins creates thread for each of them to wait, will try to check.

**Comment by almiroshnich** [comment]
@terma 
I might be wrong with my assumption since I can't prove the relation between fleet-plugin scaling (both up&down) and blocked threads, see screenshot below.
(There are obviously much more blocked thread spikes rather than queue fluctuations)

<details>
<summary>metrics (click to expand)</summary>

![image](https://user-images.githubusercontent.com/4091725/71154701-cd8e5880-2244-11ea-96de-652327052af6.png)

</details>

FYI
* I upgraded the plugin on 12/17 at ~ 08-30, all timings in UTC
* other metrics are disabled on the graphs for visibility

**Comment by terma** [comment]
@almiroshnich nice pic, can we expand chart for two days, just interesting to see diff between day and night. Interesting, let me test my jenkins =)
