### ISSUE TITLE
Fleet plugin throws java.util.concurrent.CancellationException and overprovisions

### ISSUE THREAD

**Issue by webminster** [jenkinsci/ec2-fleet-plugin#167]
Note: I filed a bug report on Jenkins JIRA: JENKINS-60715 but no comments there.  Trying here.

I have a build autoscaling group with min=0.  Frequently when Jenkins queues a job, the ec2-fleet plugin throws an exception provisioning a slave instance, and tries again.  However, there was no issue with the first instance launching - now I have 2 build instances running, and wasting money.

Usually the issue is shown in the logs as follows:
2020-01-21 23:33:56.414+0000 [id=36]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: currentDemand 1 availableCapacity 0 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 0 additionalPlannedCapacity 0)
2020-01-21 23:33:56.415+0000 [id=36]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] excessWorkload 1
2020-01-21 23:33:56.415+0000 [id=36]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] to provision = 1
2020-01-21 23:33:56.415+0000 [id=36]    INFO    h.s.NodeProvisioner$StandardStrategyImpl#apply: Started provisioning FleetNode-0 from FleetCloud with 5 executors. Remaining excess workload: -4
2020-01-21 23:33:56.906+0000 [id=30]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] fleet instances []
2020-01-21 23:33:56.906+0000 [id=30]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] described instances []
2020-01-21 23:33:56.906+0000 [id=30]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] jenkins nodes []
2020-01-21 23:33:56.906+0000 [id=30]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] jenkins nodes without instance []
2020-01-21 23:33:56.906+0000 [id=30]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] terminated instances []
2020-01-21 23:33:56.907+0000 [id=30]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] new instances []
2020-01-21 23:34:06.177+0000 [id=25]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] start
2020-01-21 23:34:06.414+0000 [id=31]    SEVERE  hudson.slaves.NodeProvisioner#lambda$update$6: Unexpected uncaught exception encountered while processing agent FleetNode-0
java.util.concurrent.CancellationException: Task was cancelled.
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:295)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:276)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:111)
        at hudson.slaves.NodeProvisioner.lambda$update$6(NodeProvisioner.java:236)
        at hudson.model.Queue._withLock(Queue.java:1392)
        at hudson.model.Queue.withLock(Queue.java:1269)
        at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:223)
        at hudson.slaves.NodeProvisioner.access$900(NodeProvisioner.java:63)
        at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:817)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:70)
        at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-01-21 23:34:06.415+0000 [id=31]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: currentDemand 1 availableCapacity 0 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 0 additionalPlannedCapacity 0)

**Comment by terma** [comment]
What are plugin and Jenkins versions?

**Comment by webminster** [comment]
Jenkins version: LTS 2.204.1 (on Ubuntu 18.04LTS)
Plugin version: 1.17.2 (same behavior on 1.17.1)
-Alan

**Comment by webminster** [comment]
Jenkins version: LTS 2.204.1 (on Ubuntu 18.04LTS)
Plugin version: 1.17.2 (same behavior on 1.17.1)
-Alan

**Comment by terma** [comment]
Do you see any logs with ```Update fleet target capacity``` could you please attach logs between two message below (some kind of full cycle of plugin work):

```
2020-01-21 23:34:06.177+0000 [id=25] INFO c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] start
```

**Comment by terma** [comment]
One more question logs below shows that no instances were described from ASG, did you see them in Console?

```
2020-01-21 23:33:56.906+0000 [id=30] INFO c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] fleet instances []
2020-01-21 23:33:56.906+0000 [id=30] INFO c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] described instances []
2020-01-21 23:33:56.906+0000 [id=30] INFO c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] jenkins nodes []
2020-01-21 23:33:56.906+0000 [id=30] INFO c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] jenkins nodes without instance []
2020-01-21 23:33:56.906+0000 [id=30] INFO c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] terminated instances []
2020-01-21 23:33:56.907+0000 [id=30] INFO c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] new instances []
```

**Comment by webminster** [comment]
I've attached a longer set of logs, trying to start the log trail right before a job started (fleet count is 0), and past the point where the job completed, and left behind two EC2 instances to idle out.
Yes, I see the empty list of fleet instances most of the time, since the min/desired count is 0.  Not sure which console you mean by "Console".

See attached, please let me know how more I can help debug.  Thanks.
[logs.txt](https://github.com/jenkinsci/ec2-fleet-plugin/files/4100452/logs.txt)

**Comment by terma** [comment]
Sorry was unclear: Console => AWS UI

**Comment by terma** [comment]
Ok, I think I found reason of this error. Looks like plugin doesn't handle correctly case when Jenkins request more capacity during sync cycle (each ```10 sec``` by default)

https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java#L437

```plannedNodesCache``` could be updated because of provision while ```targetCapacity``` is static, so we need to check against ```toAdd```

**Comment by terma** [comment]
Ok, fixed in [1.17.3](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.17.3)

**Comment by webminster** [comment]
Yes, I saw the update package.  Will be trying it out today and will report.
Thanks so much for looking into this!

**Comment by webminster** [comment]
This change looks like it fixed the problem, have not gotten any extra spinups on my two test clusters.  Thanks very much for the help!

**Comment by terma** [comment]
Nice, yw
