### ISSUE TITLE
Issue with number of API requests

### ISSUE THREAD

**Issue by Shasthri** [jenkinsci/ec2-fleet-plugin#258]
We have been observing lot of errors related to number of API calls that's being made to AWS.

```
Error during fleet docker stats update
com.amazonaws.services.ec2.model.AmazonEC2Exception: Request limit exceeded. (Service: AmazonEC2; Status Code: 503; Error Code: RequestLimitExceeded; Request ID: aaaaa-aaaaa-aaa-aaaaa-aaaaaaa; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:25450)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:25417)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:25406)
	at com.amazonaws.services.ec2.AmazonEC2Client.executeDescribeInstances(AmazonEC2Client.java:12022)
	at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:11993)
	at com.amazon.jenkins.ec2fleet.EC2Api.describeInstancesBatch(EC2Api.java:93)
	at com.amazon.jenkins.ec2fleet.EC2Api.describeInstances(EC2Api.java:72)
	at com.amazon.jenkins.ec2fleet.EC2Api.describeInstances(EC2Api.java:62)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.updateByState(EC2FleetCloud.java:502)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.update(EC2FleetCloud.java:431)
	at com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:58)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
	
We managed to increase the parameter "Cloud Status Interval in sec" from default value of 10 sec to 40-45 sec. But this is not helping much. 
Questions --

1. How many API calls is made by this plugin by default ?
2. What should be the optimum value for parameter - "Cloud Status Interval in sec" ?
3. If we use 15-20 ASG's across jenkins masters which are tied to a single AWS account, does increasing the parameter mentioned in the 2nd point really makes any difference ?

Thanks!

**Comment by jillmon** [comment]
Hello, 
We have triaged your ticket according to our team's guidelines. We should have some time to investigate next week. Thank you for your patience.

**Comment by haugenj** [comment]
👋  @Shasthri 

1. Once the plugin is running it should only make one Describe Instances request per fleet per update cycle. More API requests can be made if there's action to take with specific instances (connect, terminate, tag), but that doesn't happen as frequently and shouldn't affect the throttle rate of Describe Instances
2. I don't have any data to support a single optimal value for this field, but in my opinion the default of 10 seconds works well
3. It should make a difference, as you'd be reducing the speed of the requests which should allow the request token bucket to refill more between requests

Are you making a significant number of API requests using this account elsewhere? I'm doubtful that the plugin could make enough requests to hit the throttling limit, especially with a very slow interval of 40-45 seconds. I suggest reading the [docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/throttling.html) on request throttling and using CloudTrail in the console to check see what is calling Describe Instances so frequently

**Comment by haugenj** [comment]
Closing this for staleness, feel free to reopen if you have more questions
