### ISSUE TITLE
Ec2-Fleet terminating instance even if there's a job in progress.

### ISSUE THREAD

**Issue by HariomSaini** [jenkinsci/ec2-fleet-plugin#279]
I'm gettting this error too frequently. 

```
Cannot contact i-xxxxxx: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@527e5c3a:i-0c530b7aab484a26d": Remote call on i-xxxxxx failed. The channel is closing down or has closed down
18:06:09  Could not connect to i-xxxxxx to send interrupt signal to process

FleetCloud i-xxxxxx was marked offline: Connection was broken: java.io.EOFException
18:06:09  	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2872)
18:06:09  	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3367)
18:06:09  	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
18:06:09  	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:379)
18:06:09  	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
18:06:09  	at hudson.remoting.Command.readFrom(Command.java:142)
18:06:09  	at hudson.remoting.Command.readFrom(Command.java:128)
18:06:09  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
18:06:09  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
18:06:09  Caused: java.io.IOException: Unexpected termination of the channel
18:06:09  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
```

I have kept `Max Idle Minutes Before Scaledown=25`. Frequenty getting this error. What I think might be happening is ec2-fleet isn't checking if a job is in running state on that instance before making the call to terminate the instance.  
Reading the [docs](https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/docs/FAQ.md), indeed it isn't checking.
```
if (node.isIdle() && numNodes > minSize && (node.isIdleTooLong() || numNodes > maxSize) {
    scheduleToTerminate(node);
}
```

To Reproduce- 
1. Set `Max Idle Minutes Before Scaledown=10`
2. When there's a node running, keep track of idle time & before a minute or two less than 10 , start a new job. 
3. At 10th minute, you'll get the above error. 
## Environment Details

**Plugin Version?**
2.3.3

**Jenkins Version?**
 2.289.3

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
No

**Using No Delay Provision Strategy?**
No

**Linux or Windows?**
Linux - Jenkins master on ubuntu 20.04, similar behaviour noticed on 18.04.

**Anything else unique about your setup?**
No

**Comment by haugenj** [comment]
👋 hi @HariomSaini 

We do consider the state of running jobs on a node when using our termination logic, so I'm wondering if this is actually us terminating the node or some external error (maybe spot interruption?).

Would you be able to provide some more logs? When a node is idle the retention check logs will look like this:
> ...
2021-08-25 16:02:18.235+0000 [id=35]	INFO	c.a.j.e.EC2RetentionStrategy#check: Check if node idle i-0e71433dd43655e0d
2021-08-25 16:02:18.235+0000 [id=35]	INFO	c.a.j.e.EC2RetentionStrategy#isIdleForTooLong: Instance: FleetCloud i-0e71433dd43655e0d Age: 64042 Max Age:300000
...

and if there's a job on the node isIdleForTooLong shouldn't show up so it might look like this:
> 2021-08-25 16:04:16.694+0000 [id=62]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] jenkins nodes: [i-0e71433dd43655e0d]
2021-08-25 16:04:18.237+0000 [id=70]	INFO	c.a.j.e.EC2RetentionStrategy#check: Check if node idle i-0e71433dd43655e0d
2021-08-25 16:04:25.448+0000 [id=67]	INFO	c.a.j.ec2fleet.EC2FleetCloud#info: FleetCloud [ec2-fleet] start
