### ISSUE TITLE
Update to 2.3.5 breaks all fleets

### ISSUE THREAD

**Issue by webminster** [jenkinsci/ec2-fleet-plugin#298]
Running Jenkins LTS 2.303.2 and upgraded ec2-fleet plugin from 2.3.4 to 2.3.5.
No executors will launch after restart.  Downgrade to 2.3.4 starts things working.

Massive tracebacks in the Jenkins master logs.  See attached logs.

2021-10-13 19:49:59.736+0000 [id=50]    INFO    c.a.jenkins.ec2fleet.CloudNanny#doRun: Error during fleet 'FleetCloud' stats update
java.lang.NullPointerException
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at com.amazon.jenkins.ec2fleet.fleet.AutoScalingGroupFleet.lambda$null$0(AutoScalingGroupFleet.java:99)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)

[ec2fleet-trace.txt](https://github.com/jenkinsci/ec2-fleet-plugin/files/7340992/ec2fleet-trace.txt)

**Comment by icep87** [comment]
@haugenj The issue is still there any happens after every reload of `Configuration as Code` in Jenkins. To get it started again you have to visit `Configure Clouds` in Jenkins UI and save the settings once again.
