### ISSUE TITLE
EC2 instances dont autoscale, and load statistics graph not getting updated. 

### ISSUE THREAD

**Issue by shahmishal** [jenkinsci/ec2-fleet-plugin#324]
## Issue Details

**Describe the bug**
Unable to automatically scale up or down the instances, also the load statistics graph does not work for EC2 based labels. 

```
Feb 15, 2022 7:06:37 AM SEVERE hudson.triggers.SafeTimerTask run
Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@41ba4312 failed
java.util.UnknownFormatConversionException: Conversion = '='
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.fine(EC2FleetCloud.java:828)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.canProvision(EC2FleetCloud.java:704)
	at hudson.model.Label.getClouds(Label.java:256)
	at hudson.model.Label.isEmpty(Label.java:431)
	at jenkins.model.Jenkins.getLabels(Jenkins.java:2095)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:816)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:90)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
Timer task hudson.model.LoadStatistics$LoadStatisticsUpdater@6ebd18ad failed
java.util.UnknownFormatConversionException: Conversion = '='
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.fine(EC2FleetCloud.java:828)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.canProvision(EC2FleetCloud.java:704)
	at hudson.model.Label.getClouds(Label.java:256)
	at hudson.model.Label.isEmpty(Label.java:431)
	at jenkins.model.Jenkins.getLabels(Jenkins.java:2095)
	at hudson.model.LoadStatistics$LoadStatisticsUpdater.doRun(LoadStatistics.java:400)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:90)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Environment Details

**Plugin Version?**
2.4.1

**Jenkins Version?**
2.319.2

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
Yes

**Linux or Windows?**
Linux

**EC2Fleet Configuration as Code**
``
Paste only eC2Fleet part from plugin configuration. Mask all security concerning details. You can download it from Manage Jenkins > Configuration as Code > Download Configuration
``

**Anything else unique about your setup?**
No

**Comment by imuqtadir** [comment]
Can you fill `EC2Fleet Configuration as Code` section so we could see what parameters are you using. Also, what labels are you using?

**Comment by shahmishal** [comment]
After restarting Jenkins application, this issue was resolved.
