### ISSUE TITLE
Plugin actions are blocked by a single EC2 instance with Termination Protection

### ISSUE THREAD

**Issue by runswithd6s** [jenkinsci/ec2-fleet-plugin#327]
## Issue Details

**Describe the bug**
When a fleet node has termination protection enabled after it has been instantiated, this protection halts other actions of the plugin toward other nodes in the fleet. The fleet increases in size, but none of the new jenkins nodes are bootstraped with Jenkins agents (ssh), and the build queue simply increases. Attached is the configuration in the wild. We have a max idle time that probably allowed hosts to be pruned. I don't know specifically how we got into this mess, but removing termination protection from the one node allowed the other nodes in the ASG to be provisioned and the build queue to begin processing again.

```
17-Mar-2022 00:00:05.876 WARNING [jenkins.util.Timer [#5]] com.amazon.jenkins.ec2fleet.EC2Api.terminateInstances Failed terminating EC2 instanceId(s): i-03bab57e9d80f8b70 with following exception: The instance 'i-03bab57e9d80f8b70' may not be terminated. Modify its 'disableApiTermination' instance attribute and try again. (Service: AmazonEC2; Status Code: 400; Error Code: OperationNotPermitted; Request ID: 20d1e0f2-2559-498d-bfda-38e3e7fcfdb8; Proxy: null)
17-Mar-2022 00:00:05.876 INFO [jenkins.util.Timer [#5]] com.amazon.jenkins.ec2fleet.CloudNanny.doRun Error during fleet 'jenkins-fleet-aft' stats update
        com.amazonaws.services.ec2.model.AmazonEC2Exception: The instance 'i-03bab57e9d80f8b70' may not be terminated. Modify its 'disableApiTermination' instance attribute and try again. (Service: AmazonEC2; Status Code: 400; Error Code: OperationNotPermitted; Request ID: 20d1e0f2-2559-498d-bfda-38e3e7fcfdb8; Proxy: null)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
                at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
                at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
                at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:33614)
                at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:33581)
                at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:33570)
                at com.amazonaws.services.ec2.AmazonEC2Client.executeTerminateInstances(AmazonEC2Client.java:33145)
                at com.amazonaws.services.ec2.AmazonEC2Client.terminateInstances(AmazonEC2Client.java:33113)
                at com.amazon.jenkins.ec2fleet.EC2Api.terminateInstances(EC2Api.java:144)
                at com.amazon.jenkins.ec2fleet.EC2FleetCloud.updateByState(EC2FleetCloud.java:582)
                at com.amazon.jenkins.ec2fleet.EC2FleetCloud.update(EC2FleetCloud.java:497)
                at com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:55)
                at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:90)
                at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
17-Mar-2022 00:00:06.280 INFO [jenkins.util.Timer [#5]] com.amazon.jenkins.ec2fleet.EC2FleetCloud.info jenkins-fleet-misc [misc-fleet] Set target capacity to '1'
17-Mar-2022 00:00:15.764 INFO [jenkins.util.Timer [#4]] com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy.apply label [aft-fleet]: currentDemand 34 availableCapacity 0 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 0 additionalPlannedCapacity 0)
17-Mar-2022 00:00:15.764 INFO [jenkins.util.Timer [#4]] com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy.apply label [aft-fleet]: cloud jenkins-fleet-misc can not provision for this label, continuing...
17-Mar-2022 00:00:15.764 INFO [jenkins.util.Timer [#4]] com.amazon.jenkins.ec2fleet.EC2FleetCloud.info jenkins-fleet-aft [aft-fleet] Max instance size '50' reached. Skipping provision
17-Mar-2022 00:00:15.764 INFO [jenkins.util.Timer [#4]] com.amazon.jenkins.ec2fleet.EC2FleetCloud.info jenkins-fleet-aft [aft-fleet] Max instance size '50' reached. Skipping provision
17-Mar-2022 00:00:15.765 INFO [jenkins.util.Timer [#4]] com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy.apply label [misc-fleet]: currentDemand 1 availableCapacity 1 (availableExecutors 0 connectingExecutors 0 plannedCapacitySnapshot 1 additionalPlannedCapacity 0)
17-Mar-2022 00:00:15.765 INFO [jenkins.util.Timer [#4]] com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy.apply label [misc-fleet]: cloud jenkins-fleet-aft can not provision for this label, continuing...
17-Mar-2022 00:00:15.785 INFO [jenkins.util.Timer [#2]] com.amazon.jenkins.ec2fleet.EC2FleetCloud.info jenkins-fleet-aft [aft-fleet] Set target capacity to '50'
17-Mar-2022 00:
```

**To Reproduce**
Some speculation here on how to reproduce with a short turn-around. It's possible that all the nodes that _could_ run jobs were terminated by AWS for one reason or another (non-Spot instances). It happens, but isn't entirely common. We had been running for some time before noticing the problem, so I can't exactly be sure how we arrived in this state. Resolving it was definitely Step 6.

1. Set a low maximum target capacity for the fleet (2 or 3 for instance)
2. Set a maximum number of builds per node to a low number (1 for instance)
3. Add termination protection to one EC2 node manually after it has been instantiated
4. Launch a number of build jobs greater than # of nodes in fleet
5. Jobs will continue to stack, nodes will not  be bootstrapped
6. Remove termination protection
7. Nodes will recover and be bootstrapped, build queue will recover

## Environment Details

**Plugin Version?**
2.5.0

**Jenkins Version?**
 2.319.3

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
Yes

**Linux or Windows?**
Linux

**EC2Fleet - Snipped from config.xml **

```
  <clouds>
    <com.amazon.jenkins.ec2fleet.EC2FleetCloud plugin="ec2-fleet@2.5.0">
      <name>jenkins-fleet-aft</name>
      <awsCredentialsId></awsCredentialsId>
      <region>us-east-1</region>
      <endpoint></endpoint>
      <fleet>jenkins-fleet-aft-AppAutoScalingGroupASGAD8B5D4B-1GH7J2R4ZMZ2Q</fleet>
      <fsRoot>/home/jenkins</fsRoot>
      <computerConnector class="hudson.plugins.sshslaves.SSHConnector" plugin="ssh-slaves@1.33.0">
        <port>22</port>
        <credentialsId>[REDACTED]</credentialsId>
        <launchTimeoutSeconds>60</launchTimeoutSeconds>
        <maxNumRetries>10</maxNumRetries>
        <retryWaitTime>15</retryWaitTime>
        <sshHostKeyVerificationStrategy class="[REDACTED]"/>
        <tcpNoDelay>true</tcpNoDelay>
      </computerConnector>
      <privateIpUsed>true</privateIpUsed>
      <alwaysReconnect>false</alwaysReconnect>
      <labelString>aft-fleet</labelString>
      <idleMinutes>15</idleMinutes>
      <minSize>0</minSize>
      <maxSize>50</maxSize>
      <minSpareSize>0</minSpareSize>
      <numExecutors>1</numExecutors>
      <addNodeOnlyIfRunning>false</addNodeOnlyIfRunning>
      <restrictUsage>true</restrictUsage>
      <scaleExecutorsByWeight>false</scaleExecutorsByWeight>
      <initOnlineTimeoutSec>180</initOnlineTimeoutSec>
      <cloudStatusIntervalSec>10</cloudStatusIntervalSec>
      <maxTotalUses>-1</maxTotalUses>
      <disableTaskResubmit>false</disableTaskResubmit>
      <noDelayProvision>false</noDelayProvision>
    </com.amazon.jenkins.ec2fleet.EC2FleetCloud>
    <com.amazon.jenkins.ec2fleet.EC2FleetCloud plugin="ec2-fleet@2.5.0">
      <name>jenkins-fleet-misc</name>
      <awsCredentialsId></awsCredentialsId>
      <region>us-east-1</region>
      <endpoint></endpoint>
      <fleet>jenkins-fleet-misc-AppAutoScalingGroupASGAD8B5D4B-1KKFCHYFPKS66</fleet>
      <fsRoot>/home/jenkins</fsRoot>
      <computerConnector class="hudson.plugins.sshslaves.SSHConnector" plugin="ssh-slaves@1.33.0">
        <port>22</port>
        <credentialsId>[REDACTED]</credentialsId>
        <launchTimeoutSeconds>60</launchTimeoutSeconds>
        <maxNumRetries>10</maxNumRetries>
        <retryWaitTime>15</retryWaitTime>
        <sshHostKeyVerificationStrategy class="[REDACTED]"/>
        <tcpNoDelay>true</tcpNoDelay>
      </computerConnector>
      <privateIpUsed>true</privateIpUsed>
      <alwaysReconnect>false</alwaysReconnect>
      <labelString>misc-fleet</labelString>
      <idleMinutes>15</idleMinutes>
      <minSize>0</minSize>
      <maxSize>20</maxSize>
      <minSpareSize>0</minSpareSize>
      <numExecutors>1</numExecutors>
      <addNodeOnlyIfRunning>false</addNodeOnlyIfRunning>
      <restrictUsage>true</restrictUsage>
      <scaleExecutorsByWeight>false</scaleExecutorsByWeight>
      <initOnlineTimeoutSec>180</initOnlineTimeoutSec>
      <cloudStatusIntervalSec>10</cloudStatusIntervalSec>
      <maxTotalUses>-1</maxTotalUses>
      <disableTaskResubmit>false</disableTaskResubmit>
      <noDelayProvision>false</noDelayProvision>
    </com.amazon.jenkins.ec2fleet.EC2FleetCloud>
  </clouds>
```

**Anything else unique about your setup?**
No

**Comment by haugenj** [comment]
Is there a reason you are enabling termination protection? The plugin is not set up to handle this case as it assumes all nodes in a given fleet are interchangeable 

dev notes: 
this is happening because the failure to terminate the instance with instance protection leads to an error thrown here https://github.com/jenkinsci/ec2-fleet-plugin/blob/master/src/main/java/com/amazon/jenkins/ec2fleet/EC2Api.java#L160

the exception stops the update() for the fleet cloud before any scaling is done (we call terminate before we call provision)

**Comment by runswithd6s** [comment]
Knowing this nature of the plugin, we fired up another small cluster specifically for testing these errant jobs. Not ideal, but do-able.
