### ISSUE TITLE
EC2 instance termination using AutoScaling group 2

### ISSUE THREAD

**Issue by sergeymatsak87** [jenkinsci/ec2-fleet-plugin#337]
## Issue Details

We are using EC2-Fleet plugin with AWS EC2 spots + ASG. From time to time we are experiencing an issue related to node termination.

On AWS side spots are terminated with status instance-terminated-by-user

Please see logs from jenkins below
```
2022-06-17 16:29:18.865+0000 [id=151184]        INFO    h.r.SynchronousCommandTransport$ReaderThread#run: I/O error in channel i-0acb3109e14f9b5ee
java.io.EOFException
        at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2905)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3400)
        at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
        at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:379)
        at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
        at hudson.remoting.Command.readFrom(Command.java:142)
        at hudson.remoting.Command.readFrom(Command.java:128)
        at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
Caused: java.io.IOException: Unexpected termination of the channel
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
2022-06-17 16:29:18.976+0000 [id=151184]        INFO    c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: DISCONNECTED: JenkinsFleet i-0acb3109e14f9b5ee
2022-06-17 16:29:18.976+0000 [id=151184]        INFO    c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Skipping executable resubmission for JenkinsFleet i-0acb3109e14f9b5ee - disableTaskResubmit: true - offline: true
2022-06-17 16:29:20.711+0000 [id=45]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: JenkinsFleet [aws-fleet] Set target capacity to '2'
2022-06-17 16:29:20.758+0000 [id=95]    INFO    c.a.j.e.EC2FleetOnlineChecker#run: Node 'i-02fab728245a4e382' connected. Resolving planned node
2022-06-17 16:29:20.840+0000 [id=45]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: JenkinsFleet [aws-fleet] Fleet 'aws-fleet' no longer has the instance 'i-0acb3109e14f9b5ee'. Removing instance from Jenkins
2022-06-17 16:29:20.840+0000 [id=45]    INFO    c.a.j.e.EC2RetentionStrategy#isIdleForTooLong: Instance: JenkinsFleet i-02fab728245a4e382 Builds left: 1  Age: 15083 Max Age:120000
2022-06-17 16:29:20.840+0000 [id=156417]        INFO    c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: DISCONNECTED: JenkinsFleet i-0acb3109e14f9b5ee
2022-06-17 16:29:20.840+0000 [id=156417]        INFO    c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Skipping executable resubmission for JenkinsFleet i-0acb3109e14f9b5ee - disableTaskResubmit: true - offline: true
2022-06-17 16:29:20.841+0000 [id=45]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: JenkinsFleet [aws-fleet] Skipping label update, the Jenkins node for instance 'i-0acb3109e14f9b5ee' was null
```

```
2022-06-17 16:31:10.677+0000 [id=41]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: JenkinsFleet [aws-fleet] Set target capacity to '1'
2022-06-17 16:31:10.677+0000 [id=41]    INFO    c.a.j.e.EC2RetentionStrategy#isIdleForTooLong: Instance: JenkinsFleet i-091e4ab0cb6b366d0 Builds left: 1  Age: 9889 Max Age:120000
2022-06-17 16:31:10.678+0000 [id=41]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: JenkinsFleet [aws-fleet] Terminating nodes: [i-02fab728245a4e382]
2022-06-17 16:31:10.682+0000 [id=156415]        INFO    c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: DISCONNECTED: JenkinsFleet i-02fab728245a4e382
2022-06-17 16:31:10.682+0000 [id=156415]        INFO    c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Skipping executable resubmission for JenkinsFleet i-02fab728245a4e382 - disableTaskResubmit: true - offline: true
2022-06-17 16:31:10.920+0000 [id=156431]        INFO    c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: DISCONNECTED: JenkinsFleet i-02fab728245a4e382
2022-06-17 16:31:10.920+0000 [id=156431]        INFO    c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Skipping executable resubmission for JenkinsFleet i-02fab728245a4e382 - disableTaskResubmit: true - offline: true
```
Jenkins UI side
```
JenkinsFleet i-03144424368f7cb9b was marked offline: Node is being removed
JenkinsFleet i-03144424368f7cb9b was marked offline: Node is being removed
JenkinsFleet i-03144424368f7cb9b was marked offline: Node is being removed
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Tests Regression)
Stage "Tests Regression" skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Fri Jun 17 20:00:52 IDT 2022 by Thread[jenkins.util.Timer [#6],5,main] [id=43]
		at hudson.model.Computer.recordTermination(Computer.java:236)
		at jenkins.model.Nodes$5.run(Nodes.java:275)
		at hudson.model.Queue._withLock(Queue.java:1395)
		at hudson.model.Queue.withLock(Queue.java:1269)
		at jenkins.model.Nodes.removeNode(Nodes.java:270)
		at jenkins.model.Jenkins.removeNode(Jenkins.java:2213)
		at com.amazon.jenkins.ec2fleet.EC2FleetCloud.removeNode(EC2FleetCloud.java:765)
		at com.amazon.jenkins.ec2fleet.EC2FleetCloud.updateByState(EC2FleetCloud.java:632)
		at com.amazon.jenkins.ec2fleet.EC2FleetCloud.update(EC2FleetCloud.java:497)
		at com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:55)
		at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:92)
		at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Also:   hudson.model.Computer$TerminationRequest: Termination requested at Fri Jun 17 20:00:52 IDT 2022 by Thread[jenkins.util.Timer [#6],5,main] [id=43]
		at hudson.model.Computer.recordTermination(Computer.java:236)
		at hudson.model.Computer.disconnect(Computer.java:504)
		at hudson.slaves.SlaveComputer.disconnect(SlaveComputer.java:775)
		at jenkins.model.Nodes$5.run(Nodes.java:276)
		at hudson.model.Queue._withLock(Queue.java:1395)
		at hudson.model.Queue.withLock(Queue.java:1269)
		at jenkins.model.Nodes.removeNode(Nodes.java:270)
		at jenkins.model.Jenkins.removeNode(Jenkins.java:2213)
		at com.amazon.jenkins.ec2fleet.EC2FleetCloud.removeNode(EC2FleetCloud.java:765)
		at com.amazon.jenkins.ec2fleet.EC2FleetCloud.updateByState(EC2FleetCloud.java:632)
		at com.amazon.jenkins.ec2fleet.EC2FleetCloud.update(EC2FleetCloud.java:497)
		at com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:55)
		at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:92)
		at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Also:   	Also:   <cycle to hudson.model.Computer$TerminationRequest: Termination requested at Fri Jun 17 20:00:52 IDT 2022 by Thread[jenkins.util.Timer [#6],5,main] [id=43]>
	Also:   <cycle to hudson.model.Computer$TerminationRequest: Termination requested at Fri Jun 17 20:00:52 IDT 2022 by Thread[jenkins.util.Timer [#6],5,main] [id=43]>
	Also:   		Also:   <cycle to hudson.model.Computer$TerminationRequest: Termination requested at Fri Jun 17 20:00:52 IDT 2022 by Thread[jenkins.util.Timer [#6],5,main] [id=43]>
		Also:   <cycle to hudson.model.Computer$TerminationRequest: Termination requested at Fri Jun 17 20:00:52 IDT 2022 by Thread[jenkins.util.Timer [#6],5,main] [id=43]>
java.io.IOException: Unable to create live FilePath for i-03144424368f7cb9b
	Also:   		Also:   <cycle to hudson.model.Computer$TerminationRequest: Termination requested at Fri Jun 17 20:00:52 IDT 2022 by Thread[jenkins.util.Timer [#6],5,main] [id=43]>
		Also:   <cycle to hudson.model.Computer$TerminationRequest: Termination requested at Fri Jun 17 20:00:52 IDT 2022 by Thread[jenkins.util.Timer [#6],5,main] [id=43]>
java.io.IOException: Unable to create live FilePath for i-03144424368f7cb9b
java.io.IOException: Unable to create live FilePath for i-03144424368f7cb9b
		at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:66)
		at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:48)
```

Would appreciate for the quick feedback

## Environment Details

**Plugin Version?**
2.5.1

**Jenkins Version?**
2.332.2

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
NO

**Linux or Windows?**
Linux

**EC2Fleet Configuration as Code**
```
         clouds:
          - eC2Fleet:
              addNodeOnlyIfRunning: false
              alwaysReconnect: false
              awsCredentialsId: "aws-creds"
              cloudStatusIntervalSec: 10
              computerConnector:
                sSHConnector:
                  credentialsId: "node-ssh-key"
                  launchTimeoutSeconds: 60
                  maxNumRetries: 10
                  port: 22
                  retryWaitTime: 15
                  sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
              disableTaskResubmit: true
              fleet: "JenkinsFleet-CI-aws-spot"
              fsRoot: "/home/root"
              idleMinutes: 2
              initOnlineCheckIntervalSec: 15
              initOnlineTimeoutSec: 180
              labelString: "aws-fleet"
              maxSize: 350
              maxTotalUses: -1
              minSize: 1
              minSpareSize: 1
              name: "JenkinsFleet"
              noDelayProvision: true
              numExecutors: 1
              oldId: "9s46c4d8-24bc-4413-bc05-476s7f2ba3d5"
              privateIpUsed: true
              region: "us-east-1"
              restrictUsage: true
              scaleExecutorsByWeight: false
```
**Anything else unique about your setup?**
No

**Comment by aviorma** [comment]
+1

**Comment by JoshStutts** [comment]
+1, experiencing essentially this exact same issue.

**Comment by limasilet** [comment]
+1

**Comment by JonasHornung** [comment]
+1 I currently have the exact same behaviour, but with Spot-Fleets

**Comment by simpod6** [comment]
+1 same issue. Is there any update on this?
