### ISSUE TITLE
Possibility to set Node Parameters per eC2Fleet

### ISSUE THREAD

**Issue by aluczakSumo** [jenkinsci/ec2-fleet-plugin#340]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to add nodeProperties to an eC2Fleet node, which prevents us from setting specific environment variables per node.  We're using JCasC to setup the nodes and it's a feature that already works for EC2 Plugin and for regular nodes.

**Describe the solution you'd like**
It would be best if it was possible to set it up as in the following example:

```
  clouds:
    - eC2Fleet:
        name: "node-name"
        fleet: "fleet-name"
        labelString: "example label"
        nodeProperties:
        - envVars:
            env:
            - key: "NUM_EXECUTORS"
              value: 1
        minSize: 0
        maxSize: 120
        maxTotalUses: 50
        numExecutors: 1
```

The nodes in the EC2Fleet seem to be already created with nodeProperties, it's just not possible to set it this way:
https://github.com/jenkinsci/ec2-fleet-plugin/blob/98962e16de2694c87098de2df5b9a38897f94824/src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java#L814
I imagine it would be possible to use parameters provided in the yaml file.

**Describe alternatives you've considered**
There are no great alternatives to this solution - some parameter can be passed using the labelString and then parsed during the job execution, but it's far from an ideal solution.

**Additional context**
For reference, when trying to set it up as in the EC2 Plugin, the following exception is thrown:

```FATAL: jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class com.amazon.jenkins.ec2fleet.EC2FleetCloud : nodeProperties.
Available attributes : addNodeOnlyIfRunning, alwaysReconnect, awsCredentialsId, cloudStatusIntervalSec, computerConnector, credentialsId, disableTaskResubmit, endpoint, fleet, fsRoot, idleMinutes, initOnlineCheckIntervalSec, initOnlineTimeoutSec, labelString, maxSize, maxTotalUses, minSize, minSpareSize, name, noDelayProvision, numExecutors, oldId, privateIpUsed, region, restrictUsage, scaleExecutorsByWeight
	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:375)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:364)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:275)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:82)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$doConfigure$16668e2$1(HeteroDescribableConfigurator.java:277)
	at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.doConfigure(HeteroDescribableConfigurator.java:277)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$null$2(HeteroDescribableConfigurator.java:86)
	at io.vavr.control.Option.map(Option.java:392)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:86)
	at io.vavr.Tuple2.apply(Tuple2.java:238)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:343)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:286)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:776)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:712) 
```

**Comment by aluczakSumo** [comment]
Hi, 
is there some update on this issue? It's blocking us from using this plugin with our current setup.

**Comment by brycahta** [comment]
Hi @aluczakSumo , thanks for the feature request. I agree this would be useful; however, I can't say when we would be able to work on this. Would you be open to submitting a PR?

**Comment by aluczakSumo** [comment]
Hi @brycahta, yes, we were even discussing it already - If you won't find the time yourself, perhaps we would be able to contribute next quarter.

**Comment by kintarowins** [comment]
I need this as well. Give me some pointers on where to make the changes to get started quickly and I'll submit a PR.
