### ISSUE TITLE
AWS terminates instances under load

### ISSUE THREAD

**Issue by delgod** [jenkinsci/ec2-fleet-plugin#36]
When I have plenty of idle instances (see issue https://github.com/jenkinsci/ec2-fleet-plugin/issues/35), plugin starts to actively down-scale instances and AWS accidentally terminate some instances with running jobs.
In result:
1. I have broken jobs with the following error:
    ```
    FATAL: java.io.IOException: Unexpected termination of the channel
    java.io.EOFException
    	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2678)
    ...
    Caused: hudson.remoting.RequestAbortedException
    ...
    Agent went offline during the build
    ```
2. I have offline instances (common issue, see also https://github.com/jenkinsci/ec2-fleet-plugin/issues/11)

The situation happens only when I have a lot of idle instances (more than 10-20).

**Comment by delgod** [comment]
can be connected to https://github.com/jenkinsci/ec2-fleet-plugin/issues/37

**Comment by terma** [comment]
Hi @delgod, Termination fix was released under version [1.1.8](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.1.8). Did it fix this issue?

**Comment by delgod** [comment]
sorry, due to this bug I was decided to use https://plugins.jenkins.io/ec2 plugin (it also has bugs).

**Comment by terma** [comment]
@delgod nw, I will try to test it and close if it was fixed.

**Comment by delgod** [comment]
Steps to Reproduce:
set minimal amount on workers - `0`
choose AMI with very long start duration (like CentOS)
wait till you have 0 workers
a run job which requires plenty of workers (like 50 workers)


result was:
plugin started ~55 workers (because of instance startup had long duration)
after 50 workers become used -- plugin started to do scale down
and killed workers under load

**Comment by terma** [comment]
@delgod thx for steps, I have reopen issue to test and try to fix

**Comment by terma** [comment]
https://jenkins.io/doc/developer/testing/ to emulate steps as integration test

**Comment by terma** [comment]
@delgod im trying to reproduce, question: under load means executors on those workers still are doing some jobs, correct?

**Comment by delgod** [comment]
yes

**Comment by terma** [comment]
@delgod what do you have for configuration item ```Max Idle Minutes Before Scaledown```? Empty, ```0```?

**Comment by terma** [comment]
@delgod I think I found the problem, according to plugin logic, the node could be removed if last execution on this node was too far (settings) however we don't check if a node has any build in progress. Unfortunately, Jenkins logic is really complicated about that so I cannot give ```100%```, so I made a fix based on Jenkins examples.

Fix released under version [1.4.1](https://github.com/jenkinsci/ec2-fleet-plugin/releases/tag/ec2-fleet-1.4.1)

I will keep the issue open, please ping if you can try, thx a lot

**Comment by delgod** [comment]
job duration is 30-60 minutes and "Max Idle Minutes Before Scaledown" was 5 minutes.
sorry, now, another person is the maintainer of CI/CD env, so cannot recheck my case.

thank you for your work!

**Comment by terma** [comment]
np, thx for reporting.

 I think fix is applucable for your case, idle time less tgen job duration, for now it checks if any job in progress too.

**Comment by jupeter** [comment]
Hi all, 
i discovered this issue today. 
I have "EC2 Fleet" spot plugin in "1.12.0" version.
Found in logs:
~~~
2019-10-17 02:24:44.848+0000 [id=217195]        INFO    c.a.j.e.EC2FleetAutoResubmitComputerLauncher#afterDisconnect: Unexpected EC2 Fleet Spot CompilationServer VS 2010 i-0954d8250872ce6c0 termination, resubmit finished
2019-10-17 02:24:45.027+0000 [id=227367]        INFO    h.r.SynchronousCommandTransport$ReaderThread#run: I/O error in channel i-09140f54c5e375ce9
java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2680)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3155)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:861)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:357)
        at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
        at hudson.remoting.Command.readFrom(Command.java:140)
        at hudson.remoting.Command.readFrom(Command.java:126)
        at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
~~~
As a resuts Node instance have state "suspended" and not shutdown.

Let me know if I can somehow give you more valuable infromation.
