### ISSUE TITLE
SpotAgent [slave] Unable to set label on node

### ISSUE THREAD

**Issue by Wensink** [jenkinsci/ec2-fleet-plugin#380]
## Issue Details
After upgrading to the latest Jenkins LTS and the ec2-fleet plugin v2.7.0 the created agents are not connected to the master.

**Describe the bug**
The master makes logs saying SpotAgent [slave] Unable to set label on node
java.lang.NullPointerException
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.addNewSlave(EC2FleetCloud.java:855)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.access$200(EC2FleetCloud.java:61)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud$2.run(EC2FleetCloud.java:706)
	at hudson.model.Queue._withLock(Queue.java:1395)
	at hudson.model.Queue.withLock(Queue.java:1269)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.updateByState(EC2FleetCloud.java:701)
	at com.amazon.jenkins.ec2fleet.EC2FleetCloud.update(EC2FleetCloud.java:513)
	at com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:55)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:92)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**To Reproduce**
Still trying to recreate our setup from scratch in another AWS account to see how it goes
1. 
2. 
etc.

## Environment Details

**Plugin Version?**
2.7.0

**Jenkins Version?**
2.401.2

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
Yes

**Linux or Windows?**
Linux

**EC2Fleet Configuration as Code**
``
  clouds:
  - eC2Fleet:
      addNodeOnlyIfRunning: false
      alwaysReconnect: true
      cloudStatusIntervalSec: 10
      computerConnector:
        sSHConnector:
          credentialsId: "xxx"
          launchTimeoutSeconds: 60
          maxNumRetries: 100
          port: 22
          retryWaitTime: 15
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      disableTaskResubmit: false
      fleet: "jenkins-agent-asg"
      fsRoot: "/home/jenkins-build/"
      idleMinutes: 30
      initOnlineCheckIntervalSec: 15
      initOnlineTimeoutSec: 180
      labelString: "slave"
      maxSize: 10
      minSize: 0
      minSpareSize: 0
      name: "SpotAgent"
      noDelayProvision: false
      numExecutors: 3
      oldId: "xxx"
      privateIpUsed: true
      region: "eu-west-1"
      restrictUsage: true
      scaleExecutorsByWeight: false

``

**Anything else unique about your setup?**

**Comment by pdk27** [comment]
@Wensink I was able to create a new agent from v2.7.0 of the plugin. Not able to reproduce this.  
I noticed that the config `maxTotalUses` is missing from your cloud configuration. If you don't have a specific value configured, it should show the default value like `maxTotalUses: -1`. Can you try adding it?

**Comment by Wensink** [comment]
Thanks for replying. 
I added the value, and now I do see agents popping up in Jenkins. Will do som further testing since I did a lot of changes to figure things out. I'll come back to you if it keeps working after applying GH master again

**Comment by Wensink** [comment]
It keeps working now. So thank you for helping me out
