### ISSUE TITLE
NoDelayProvisionStrategy won't provision after scaling down to 0 instances in auto scaling group

### ISSUE THREAD

**Issue by cccCody** [jenkinsci/ec2-fleet-plugin#425]
I think this is the same issue as https://github.com/jenkinsci/ec2-fleet-plugin/issues/180

**Describe the bug**
I'm currently trying to move from ec2-plugin to this plugin, but I'm seeing that the final stage of my build doesn't ever get an executor. My build looks roughly like this:

1. build step on a single node
2. test in parallel on several nodes (150 of them!)
3. collect coverage reports on a single node

Everything works nicely until the last step, where it gets stuck on:
```
Waiting for next available executor on ec2-fleet
```
When I check the system logs, I see this on repeat:
```
Nov 21, 2023 3:08:12 PM FINE com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy apply
label [ec2-fleet]: queueLength 1 availableCapacity 1 (availableExecutors 0 plannedCapacitySnapshot 1 additionalPlannedCapacity 0)
Nov 21, 2023 3:08:12 PM INFO com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy apply
label [ec2-fleet]: No excess workload, provisioning not needed.
```

I'm especially suspicious of `plannedCapacitySnapshot 1`, which, if I'm reading [the source code](https://github.com/jenkinsci/ec2-fleet-plugin/blob/cd675868e5bc3a39c9fcdb704ca5a4d018a7272e/src/main/java/com/amazon/jenkins/ec2fleet/NoDelayProvisionStrategy.java#L34) right, seems to mean that it thinks it's already started scaling up another node (and is waiting for it to come online (?)) but it never does.

Other misc info, may or may not be relevant:
- All steps use the same label ("ec2-fleet") and run one executor per node.
- cloud configuration includes:
  - Minimum Cluster Size: 0
  - Maximum Cluster Size: 2000
  - Minimum Spare Size: 0
  - Maximum Total Uses: 1

## Environment Details

**Plugin Version?**
3.1.0 (latest as of opening this)

**Jenkins Version?**
2.426.1 (latest LTS version as of opening this issue)

**Spot Fleet or ASG?**
ASG

**Label based fleet?**
no

**Linux or Windows?**
linux

**Comment by cccCody** [comment]
Setting "Minimum Spare Size" to 1 works as a workaround, but I'd rather not leave an unused instance running 24/7.

**Comment by icep87** [comment]
We are also seeing this issue. When there are no agents available, meaning they are all scale down. The plugin won
t spin up agents at all. 

In the logs it says: 

```
Nov 22, 2023 7:02:32 PM FINE com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy
label [linux]: queueLength 1 availableCapacity 1 (availableExecutors 0 plannedCapacitySnapshot 1 additionalPlannedCapacity 0)
Nov 22, 2023 7:02:32 PM INFO com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy apply
label [linux]: No excess workload, provisioning not needed.
Nov 22, 2023 7:02:32 PM FINE com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy
label [powerful]: queueLength 1 availableCapacity 1 (availableExecutors 0 plannedCapacitySnapshot 1 additionalPlannedCapacity 0)
Nov 22, 2023 7:02:32 PM INFO com.amazon.jenkins.ec2fleet.NoDelayProvisionStrategy apply
label [powerful]: No excess workload, provisioning not needed.
```

I'm wondering why it actually says that there is availableCapacity when clearly there is none and no scale up is triggered.

**Comment by icep87** [comment]
@cccCody Did you manage to find the cause of this?

**Comment by snowman-papa** [comment]
I encountered a similar problem
I tried the jenkins script console

```
Jenkins jenkins = Jenkins.getInstance()

jenkins.getLabels().each { Label label ->
    def nodeProvisioner = label.nodeProvisioner
    def pendingLaunches = nodeProvisioner.getPendingLaunches()

     if (pendingLaunches.size() == 0) {
    	return
     }

    println("Label: ${label.name}")
    pendingLaunches.each {
        println("  Planned Node: ${it.displayName}, Executors: ${it.numExecutors}")
    }
}
```

Output
```
Label: xxx
  Planned Node: NodeName-xx, Executors: 1
  Planned Node: NodeName-xx, Executors: 1
```

There were no jobs running
Restarting jenkins solved it

**Comment by opajonk** [comment]
I think we are running into the same issue here, with the NoDelayProvisioningStrategy. Digging around in the issues I found https://github.com/jenkinsci/ec2-fleet-plugin/issues/149 - this one reads like a regression. Could that be?

**Comment by pawel-t** [comment]
I have faced the same issue on 3.2.0. 

Once we have switched to ASG from SpotFleet. My SpotFleet was setup with Min = 0 and Spare = 0 and after it scaled down to 0 instance. For 1.5h it didn't scale up while jobs were waiting in queue. 

I needed to increase min and spare in order it to work.

**Comment by ldmonkey** [comment]
We downgraded the plugin from 3.2.0 to 3.0.1. Waiting for a fix for this issue.

**Comment by icep87** [comment]
The issue is actually occurring in the NodeProvisioner. We could not find any errors of failed launch in the EC2-Fleet plugins. Instead, the NodeProvisioner has stale nodes planned. This could be fixed by the plugin by monitoring which nodes are planned by the NodeProvisioner and removing them if they haven’t come up after a defined time. Currently, NodeProvisioner does not provide any kind of timestamp indicating when the planned node was requested. Making it quite hard to find without a function that can monitor it. 

As mentioned by @taka-papa, you can run the script to see if there are any planned launches of nodes. 
If you have staled nodes and want to solve the issue and avoid restarting Jenkins, here is a script that will help you remove the planned launches.

```
import jenkins.model.Jenkins
import hudson.model.Label
import hudson.slaves.NodeProvisioner

Jenkins jenkins = Jenkins.getInstance()

def labelToReset = "LABEL OF THE CLOUDNODES"

jenkins.getLabels().each { Label label ->
    if (label.name == labelToReset) {
        def nodeProvisioner = label.nodeProvisioner
        def pendingLaunches = nodeProvisioner.getPendingLaunches()

        if (pendingLaunches.size() > 0) {
            println("Cancelling pending launches for label: ${label.name}")
            pendingLaunches.each { launch ->
                launch.future.cancel(true)
                println("Cancelled launch: ${launch.displayName}")
            }
        } else {
            println("No pending launches to cancel for label: ${label.name}")
        }
    }
}

return "Cancellation process completed."
```

**Comment by wosiu** [comment]
@icep87 What do you mean by "(...) has stale nodes planned"? 
Any chances you dig into why they don't "come up after a defined time"?

**Comment by icep87** [comment]
@wosiu What I mean is that the nodes get stuck in PendingLaunch. They never leave that state. I could not find any errors in the logs, and as this issue is hard to reproduce it makes it difficult to debug. But as soon as I have the chance I will try to debug it. 

For example we haven't had this issue for more than 2 weeks now.

**Comment by PW999** [comment]
I'm constantly having issues with the NoDelayProvisionStrategy.

Right now it says the target is 3
![image](https://github.com/user-attachments/assets/3251e409-8395-4d8e-b803-19be354833cb)

Yet in AWS the desired size is 1
![image](https://github.com/user-attachments/assets/56f112c4-f670-4260-ae1a-c04460018979)

and there is a single instance running, but it doesn't show up in Jenkins at all. 
So if you need any specific debug logs, just let me know ;)

**Comment by ebarped** [comment]
> We downgraded the plugin from 3.2.0 to 3.0.1. Waiting for a fix for this issue.

We are waiting for this issue to be fixed to start using this plugin. @ldmonkey does the version `3.0.1` work properly?

**Comment by dsakilesh** [comment]
We also face the same issue. We downgraded to 3.0.1 with no luck. Was anyone able to solve the issue? Or any workaround for this issue?

**Comment by BradyShober** [comment]
@chill389cc Thanks for that detail, unfortunately in my dev environment that does not seem to trigger the behavior. Is there any other detail about your environment that may be relevant?

Also I believe I already know what the log output will be, but could you configure a logger for com.amazon.jenkins.ec2fleet at the FINE level and you should see some additional log output.

**Comment by pral1kor** [comment]
Hello @BradyShober,

I still see this error on my Jenkins. Here is my Jenkins environment details.

Jenkins master Version: 2.555.1
EC2Fleet version: 4.2.3.539.v8fedff2a_81c3

I start a job with label 'light_linux_spot', following fleet logs are seen

INFO    c.a.j.e.NoDelayProvisionStrategy#apply: Started provisioning FleetNode-light_linux_spot-1 from light_linux_spot with 1 executors. Remaining excess workload: 0
2026-05-08 05:26:30.106+0000 [id=57]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: light_linux_spot [light_linux_spot] Set target capacity to '1'
2026-05-08 05:26:30.456+0000 [id=52]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed.
2026-05-08 05:26:40.456+0000 [id=52]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed.
2026-05-08 05:26:50.456+0000 [id=47]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed.
2026-05-08 05:27:00.456+0000 [id=57]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed.
2026-05-08 05:27:10.456+0000 [id=57]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed


After few minutes...

`2026-05-08 05:30:00.456+0000 [id=57]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed.
2026-05-08 05:30:09.995+0000 [id=50]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: light_linux_spot [light_linux_spot] Planned number of nodes '1' is greater than the targetCapacity '0'. Canceling a node
2026-05-08 05:30:10.456+0000 [id=45]    SEVERE  hudson.slaves.NodeProvisioner#update: Unexpected uncaught exception encountered while processing agent FleetNode-light_linux_spot-1
java.util.concurrent.CancellationException
        at java.base/java.util.concurrent.CompletableFuture.cancel(Unknown Source)
        at PluginClassLoader for ec2-fleet//com.amazon.jenkins.ec2fleet.EC2FleetCloud.update(EC2FleetCloud.java:536)
        at PluginClassLoader for ec2-fleet//com.amazon.jenkins.ec2fleet.CloudNanny.doRun(CloudNanny.java:58)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:92)
        at jenkins.security.ImpersonatingScheduledExecutorService.lambda$wrap$0(ImpersonatingScheduledExecutorService.java:65)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2026-05-08 05:30:10.457+0000 [id=45]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: Started provisioning FleetNode-light_linux_spot-2 from light_linux_spot with 1 executors. Remaining excess workload: 0
2026-05-08 05:30:19.923+0000 [id=33]    INFO    c.a.j.ec2fleet.EC2FleetCloud#info: light_linux_spot [light_linux_spot] Set target capacity to '1'
2026-05-08 05:30:20.456+0000 [id=51]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed.
2026-05-08 05:30:30.456+0000 [id=52]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed.
2026-05-08 05:30:40.456+0000 [id=48]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed.
2026-05-08 05:30:50.456+0000 [id=45]    INFO    c.a.j.e.NoDelayProvisionStrategy#apply: label [light_linux_spot]: No excess workload, provisioning not needed
2026-05-08 05:35:10.483+0000 [id=50]    WARNING hudson.model.Slave#warnPlugin: com.amazon.jenkins.ec2fleet.EC2FleetNode or one of its superclass overrides readResolve() without calling super implementation.Please file an issue against the plugin implementing it: Plugin:ec2-fleet`

**Meanwhile in script console I executed following code,** 

`import jenkins.model.Jenkins
import hudson.model.Label
def jenkins = Jenkins.get()
def pendingNodes = []

jenkins.getLabels().each { label ->
    def nodeProvisioner = label.nodeProvisioner
    def pendingLaunches = nodeProvisioner.getPendingLaunches()
    if (pendingLaunches.size() > 0) {
        pendingLaunches.each { launch ->
            pendingNodes.add(launch.displayName)
            println "Pending labeled node: ${launch.displayName}, Label: ${label.name}, Executors: ${launch.numExecutors}"
        }
    }
}`

**Output:**
Pending labeled node: FleetNode-light_linux_spot-1, Label: light_linux_spot, Executors: 1

**After clearing this Pending nodes with below script, scaling instances seems to work fine**

`import jenkins.model.Jenkins
import hudson.model.Label

def jenkins = Jenkins.get()
def allLabels = jenkins.getLabels()

def nodeProvisioner = label.nodeProvisioner
def pendingLaunches = nodeProvisioner.getPendingLaunches()
  pendingLaunches.each { launch ->
    try {
      launch.future.cancel(true)
      println("Cancelled launch: ${launch.displayName}")
    } catch (Exception e) {
      println("Error cancelling node: Error: ${e.message}")
      
    }
}`

**Comment by manvith-SR** [comment]
Reproduced this on ec2-fleet 4.4.0.554.ve1d40b_c02e16 (latest, hasUpdate: false), Jenkins 2.568.2.

A queued build waited 197 minutes and would not have started on its own. Queue item, throughout:


stuck: true   buildable: true   blocked: false
why: 'Jenkins' doesn't have label 'Worker-Linux86'
Meanwhile, every 10 seconds for the entire wait — 256 of 262 lines in the window, no errors, exceptions or auth failures:


c.a.j.e.NoDelayProvisionStrategy#apply: label [Worker-Linux86]:
No excess workload, provisioning not needed.
The label resolved to exactly one cloud that could serve it, with 0 nodes and 0 executors.

Not a quota or capacity problem. The Auto Scaling group recorded zero scaling activities for the entire 197 minutes. Nothing was ever requested, so nothing was refused. (There had been VcpuLimitExceeded failures earlier that night, but they ended 6.5 hours before the build queued.)

The detail I haven't seen recorded here: restarting the controller recovers it. 87 seconds after an unrelated restart, the plugin provisioned on its own:


13:20:14  NoDelayProvisionStrategy#apply: Started provisioning FleetNode-gpu-1
          from gpu with 2 executors. Remaining excess workload: -1
13:20:24  EC2FleetCloud#info: gpu [...] Set target capacity to '1'
Nothing persisted was wrong — config, credentials and label resolution were all correct throughout, and the same plugin instance recovered the moment its in-memory state was cleared. That localises the fault to process-local state and is consistent with a stale plannedCapacitySnapshot surviving a planned node that never launched.

Preconditions: minSize: 0, pool idled down to zero 5h50m before the build queued, so the fleet was empty and at rest when demand arrived.

Workarounds that work for us: minSize: 1 avoids it entirely (matching #172), and a controller restart recovers an active stall.
