### ISSUE TITLE
UnsupportedClassVersionError: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by freshfx** [jenkinsci/ec2-fleet-plugin#50]
I try to start a spot fleet instance but get an error on ssh connection.

Jenkins v2.150.1

```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

Agent Log:
```
[01/11/19 10:20:16] [SSH] Opening SSH connection to x.x.x.x:22.
[01/11/19 10:20:16] [SSH] The SSH key with fingerprint x:x:x:x:x:x:x:x has been automatically trusted for connections to this machine.
[01/11/19 10:20:16] [SSH] Authentication successful.
[01/11/19 10:20:16] [SSH] The remote user's environment is:
AWS_AUTO_SCALING_HOME=/opt/aws/apitools/as
AWS_CLOUDWATCH_HOME=/opt/aws/apitools/mon
AWS_ELB_HOME=/opt/aws/apitools/elb
AWS_PATH=/opt/aws
BASH=/bin/bash
BASHOPTS=cmdhist:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
BASH_VERSINFO=([0]="4" [1]="2" [2]="46" [3]="2" [4]="release" [5]="x86_64-redhat-linux-gnu")
BASH_VERSION='4.2.46(2)-release'
DIRSTACK=()
EC2_AMITOOL_HOME=/opt/aws/amitools/ec2
EC2_HOME=/opt/aws/apitools/ec2
EUID=500
GROUPS=()
HOME=/home/ec2-user
HOSTNAME=ip-x-x-x-x
HOSTTYPE=x86_64
ID=500
IFS=$' \t\n'
JAVA_HOME=/usr/lib/jvm/jre
LANG=en_US.UTF-8
LESSOPEN='||/usr/bin/lesspipe.sh %s'
LESS_TERMCAP_mb=$'\E[01;31m'
LESS_TERMCAP_md=$'\E[01;38;5;208m'
LESS_TERMCAP_me=$'\E[0m'
LESS_TERMCAP_se=$'\E[0m'
LESS_TERMCAP_ue=$'\E[0m'
LESS_TERMCAP_us=$'\E[04;38;5;111m'
LOGNAME=ec2-user
MACHTYPE=x86_64-redhat-linux-gnu
MAIL=/var/mail/ec2-user
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/bin:/bin:/usr/bin:/opt/aws/bin
PIPESTATUS=([0]="0")
PPID=26980
PS4='+ '
PWD=/home/ec2-user
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=1
SSH_CLIENT='x.x.x.x 55306 22'
SSH_CONNECTION='x.x.x.x 55306 x.x.x.x 22'
TERM=dumb
UID=500
USER=ec2-user
_=/etc/bashrc
[01/11/19 10:20:16] [SSH] Starting sftp client.
[01/11/19 10:20:16] [SSH] Remote file system root /tmp/jenkins-d663ed22 does not exist. Will try to create it...
[01/11/19 10:20:16] [SSH] Copying latest remoting.jar...
[01/11/19 10:20:17] [SSH] Copied 776,717 bytes.
Expanded the channel window size to 4MB
[01/11/19 10:20:17] [SSH] Starting agent process: cd "/tmp/jenkins-d663ed22" && /usr/bin/java  -jar remoting.jar -workDir /tmp/jenkins-d663ed22
Exception in thread "main" java.lang.UnsupportedClassVersionError: hudson/remoting/Launcher : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Slave JVM has terminated. Exit code=1
[01/11/19 10:20:17] Launch failed - cleaning up connection
[01/11/19 10:20:17] [SSH] Connection closed.
```

**Comment by freshfx** [comment]
Solved it.
I created an AMI on AWS with java 1.8 installed and use it for requesting a spot instance.
