### ISSUE TITLE
Use an external SSH client process to connect to the slaves

### ISSUE THREAD

**Issue by thaiphv** [jenkinsci/ec2-fleet-plugin#61]
Have we ever considered this idea? I've found that the slaves getting terminated more often since I started using this plugin due to the same error pattern:
```
Apr 08, 2019 6:55:13 AM hudson.remoting.SynchronousCommandTransport$ReaderThread run
INFO: I/O error in channel i-0544c80944d28d2a7
java.io.IOException: Unexpected termination of the channel
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
Caused by: java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
        at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
        at hudson.remoting.Command.readFrom(Command.java:140)
        at hudson.remoting.Command.readFrom(Command.java:126)
        at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
        at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
```
I understand this is an issue of https://github.com/jenkinsci/remoting but it didn't happen to me when I used the https://github.com/jenkinsci/ec2-plugin with that feature turned on.

**Comment by thaiphv** [comment]
It seems https://issues.jenkins-ci.org/browse/JENKINS-55363 can fix the issue

**Comment by jillmon** [comment]
Closing for now. Please let us know if this issue is still affecting you.
